name: CI/CD Pipeline with BDD + Playwright

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

# Environment variables for consistent configuration
env:
  NODE_VERSION: '20.19'
  # NOTE: removed PLAYWRIGHT_BROWSERS_PATH to let Playwright install browsers to default location.
  # If you need a custom path, add it and ensure npx playwright install respects it.

jobs:
  # Unit Tests
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run type checking
      run: npm run type-check

    - name: Run unit tests with coverage
      run: npm run test:coverage

    - name: Upload coverage reports
      uses: codecov/codecov-action@v3
      if: always()
      with:
        files: ./coverage/lcov.info
        fail_ci_if_error: false

  # Build
  build:
    name: Build Application
    runs-on: ubuntu-latest
    needs: unit-tests

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build application
      run: npm run build

    - name: Cache build output
      uses: actions/cache@v4
      with:
        path: dist
        key: build-${{ github.sha }}

  # BDD E2E Tests with Cucumber + Playwright
  bdd-e2e-tests:
    name: BDD E2E Tests (Cucumber + Playwright)
    runs-on: ubuntu-latest
    needs: unit-tests

    strategy:
      matrix:
        browser: [chromium, firefox, webkit]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    # Install Playwright browsers + system dependencies (explicit, full install)
    - name: Install Playwright browsers + deps
      run: npx playwright install --with-deps

    # OPTIONAL: debug listing of installed browsers (uncomment to help troubleshoot)
    #- name: Debug - list playwright browsers
    #  run: |
    #    echo "Playwright env:"
    #    env | grep -i PLAYWRIGHT || true
    #    npx playwright --version || true
    #    ls -la node_modules/playwright-core/.local-browsers || true

    - name: Create required directories
      run: |
        mkdir -p screenshots
        mkdir -p reports
        mkdir -p test-results

    - name: Restore build output
      uses: actions/cache@v4
      with:
        path: dist
        key: build-${{ github.sha }}

    - name: Build application if cache miss
      run: |
        if [ ! -d "dist" ]; then
          npm run build
        fi

    - name: Start application
      run: |
        npm run preview &              # start preview server in background
        echo "Started preview server"
      env:
        CI: true

    - name: Wait for server
      run: |
        npx wait-on http://localhost:4173 --timeout 60000
        echo "Server is ready"

    - name: Run BDD E2E Tests
      run: npm run test:e2e
      env:
        BROWSER: ${{ matrix.browser }}
        HEADLESS: true
        CI: true
        PARALLEL: 1

    - name: Upload test artifacts (on failure)
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: test-artifacts-${{ matrix.browser }}
        path: |
          screenshots/
          reports/
          test-results/
        retention-days: 7

    - name: Upload BDD Reports
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: bdd-reports-${{ matrix.browser }}
        path: |
          reports/cucumber_report.html
          reports/cucumber_report.json
        retention-days: 30

  # Pure Playwright Tests (if you have any)
  playwright-tests:
    name: Playwright Tests
    runs-on: ubuntu-latest
    needs: unit-tests

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Install Playwright browsers + deps
      run: npx playwright install --with-deps

    - name: Restore build output
      uses: actions/cache@v4
      with:
        path: dist
        key: build-${{ github.sha }}

    - name: Build application if cache miss
      run: |
        if [ ! -d "dist" ]; then
          npm run build
        fi

    - name: Start application
      run: npm run preview &

    - name: Wait for server
      run: npx wait-on http://localhost:4173 --timeout 60000

    - name: Run pure Playwright tests
      run: npm run test:playwright || echo "No Playwright tests found"

    - name: Upload Playwright Report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30

  # Test Results Summary
  test-summary:
    name: Test Results Summary
    runs-on: ubuntu-latest
    needs: [unit-tests, build, bdd-e2e-tests, playwright-tests]
    if: always()

    steps:
    - name: Check test results
      run: |
        echo "=== TEST RESULTS SUMMARY ==="
        echo "Unit Tests: ${{ needs.unit-tests.result }}"
        echo "Build: ${{ needs.build.result }}"
        echo "BDD E2E Tests: ${{ needs.bdd-e2e-tests.result }}"
        echo "Playwright Tests: ${{ needs.playwright-tests.result }}"

        declare -i success_count=0

        if [[ "${{ needs.unit-tests.result }}" == "success" ]]; then
          success_count+=1
        fi

        if [[ "${{ needs.build.result }}" == "success" ]]; then
          success_count+=1
        fi

        if [[ "${{ needs.bdd-e2e-tests.result }}" == "success" ]]; then
          success_count+=1
        fi

        if [[ "${{ needs.playwright-tests.result }}" == "success" || "${{ needs.playwright-tests.result }}" == "skipped" ]]; then
          success_count+=1
        fi

        echo "✅ Successful jobs: $success_count/4"

        if [[ "${{ needs.unit-tests.result }}" == "success" &&
              "${{ needs.build.result }}" == "success" &&
              "${{ needs.bdd-e2e-tests.result }}" == "success" ]]; then
          echo "🎉 All critical tests passed!"
          exit 0
        else
          echo "❌ Some critical tests failed!"
          exit 1
        fi

  # Deploy (runs only on main branch and all tests pass)
  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: [unit-tests, build, bdd-e2e-tests]
    if: github.ref == 'refs/heads/main' && needs.unit-tests.result == 'success' && needs.build.result == 'success' && needs.bdd-e2e-tests.result == 'success'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: Restore build output
      uses: actions/cache@v4
      with:
        path: dist
        key: build-${{ github.sha }}

    - name: Deploy application
      run: |
        echo "🚀 Deploying to production..."
        # Add your deployment commands here
        echo "✅ Deployment completed!"
